# Project Name
TARGET = namTest

# Set App Type
APP_TYPE = BOOT_SRAM

# Sources
CPP_SOURCES = namTest.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

CPP_STANDARD = -std=c++17
CPPFLAGS += -fexceptions